"""added some fields

Revision ID: 081b34133b62
Revises: ec196f00eb3b
Create Date: 2022-10-17 22:46:29.677614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081b34133b62'
down_revision = 'ec196f00eb3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
