"""Added a Field to save role-ID

Revision ID: 14178e5f49de
Revises: 8a7bc48b7ec6
Create Date: 2022-10-21 23:59:42.138984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14178e5f49de'
down_revision = '8a7bc48b7ec6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as bop:
        bop.alter_column('projects', 'role',
                         existing_type=sa.INTEGER(),
                         nullable=False)
    op.create_unique_constraint(None, 'projects', ['role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.alter_column('projects', 'role',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
