"""Added Leader-role field

Revision ID: 2d5ba9d3d16e
Revises: 14178e5f49de
Create Date: 2022-10-22 00:34:47.518343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5ba9d3d16e'
down_revision = '14178e5f49de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader_role', sa.Integer(), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['role'])
        batch_op.create_unique_constraint(None, ['leader_role'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('leader_role')

    # ### end Alembic commands ###
