"""empty message

Revision ID: 5021e4647900
Revises: ebb867d435b9
Create Date: 2022-10-21 15:59:22.525907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5021e4647900'
down_revision = 'ebb867d435b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('label', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'label')
    # ### end Alembic commands ###
