"""empty message

Revision ID: 8a7bc48b7ec6
Revises: 5021e4647900
Create Date: 2022-10-21 23:50:31.175718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7bc48b7ec6'
down_revision = '5021e4647900'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'repository')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('repository', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
