"""Added a repo field

Revision ID: aab46fd9fb09
Revises: 081b34133b62
Create Date: 2022-10-19 14:42:23.338591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab46fd9fb09'
down_revision = '081b34133b62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('repository', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'repository')
    # ### end Alembic commands ###
