"""empty message

Revision ID: ebb867d435b9
Revises: ec4d48ee046e
Create Date: 2022-10-21 14:49:26.475532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb867d435b9'
down_revision = 'ec4d48ee046e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
