"""Added repos

Revision ID: ec4d48ee046e
Revises: aab46fd9fb09
Create Date: 2022-10-19 15:33:28.209616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4d48ee046e'
down_revision = 'aab46fd9fb09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('projects', 'repository')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('repository', sa.VARCHAR(), nullable=True))
    op.drop_table('repos')
    # ### end Alembic commands ###
